services:

  server:
    build:
      context: ./server

    container_name: madiao-server

    ports:
      - "127.0.0.1:3001:3001"

    environment:
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}

    restart: unless-stopped


  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}

    container_name: madiao-client

    ports:
      - "127.0.0.1:3000:80"

    restart: unless-stopped

  docs:
    build: 
      context: .
      dockerfile: Dockerfile
    
    container_name: madiao-docs

    ports:
      - "127.0.0.1:3002:80"
    
    restart: unless-stopped