services:

  server:
    build:
      context: ./server

    container_name: madiao-server

    ports:
      - "3001:3001"

    environment:
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}

    restart: unless-stopped


  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}

    container_name: madiao-client

    ports:
      - "3000:80"

    restart: unless-stopped